### ISSUE TITLE
Json support

### ISSUE THREAD

**Issue by martsokha** [jgraef/reqwest-websocket#12]
- `json` feature flag/optional `serde`/`serde_json` deps
- `.json<T>()` method for `Message`.
- `Json(serde::Error)` case for `Error`.

Just let me know if the feature request gets approved, and I'll go ahead with the pull request.

**Comment by jgraef** [comment]
How would the serialization side of this look like? When sending a JSON message the user needs to decide whether to serialize the JSON as `Message::Text` or `Message::Binary`.

**Comment by jgraef** [comment]
#13 was merged

**Comment by martsokha** [comment]
where is json error type now?

**Comment by jgraef** [comment]
The `serde_json`-related methods can only fail with `serde_json::Error`, so my thought was that it doesn't make sense then to return a generic `crate::Error`, but rather return that `serde_json::Error`. Does that make sense?

To avoid having to depend on `serde_json` as a user of `reqwest-websocket` for the error type I type-aliased it as `crate::protocol::JsonError`. But I just noticed that this won't be public then. I'll re-export it as `crate::JsonError`.

**Comment by jgraef** [comment]
If you think it would be better to put the `serde_json::Error` into `crate::Error` I can revert that change. I thought it was a good idea, but I'm not so sure now.

**Comment by martsokha** [comment]
there is a reason `reqwest` returns a generic `Error`: you are not forced to use `Box<dyn Error>`/`anyhow::Error`/your custom `Error` (that combines `reqwest::Error` and `json_serde::Error`) as you can use `reqwest::Error` for any method that uses `reqwest.

**Comment by jgraef** [comment]
You're right. I changed it back.
