### ISSUE TITLE
Ping, Pong and Close frames

### ISSUE THREAD

**Issue by jgraef** [jgraef/reqwest-websocket#14]
See #10 

Implemented by [this commit](https://github.com/jgraef/reqwest-websocket/commit/25d9ffa25554afe0ab975c35ea58a4d0e064878e) (I should have opened a PR instead).

CI fails for this commit, so we'll need to fix that. I'm also working on a small WASM demo, to be able to test for WASM.

**Comment by jgraef** [comment]
WASM demo is done, and it still works :grin: 

After @martsokha 's review this should be fine for a release.

**Comment by jgraef** [comment]
I added the deprecation warning to `Ping` and `Pong` frames on WASM. But maybe we should also panic when sending those on WASM (and of course document this). What's y'all's opinion on this?

@martsokha @asabil

**Comment by martsokha** [comment]
It looks fine overall. I would avoid adding an additional error type, such as JsonError, but that's just a preference. I wouldn't panic, as it would force users into conditional compilation if the crate is intended to work on both WASM and non-WASM targets. PR #15 includes several minor fixes.

**Comment by jgraef** [comment]
The `JsonError` is required, because we can't create a `serde_json::Error`, and I'd rather have one json-related error, instead of adding `NeitherTextNorBinaryMessage` to `crate::Error`.

**Comment by martsokha** [comment]
We can, `serde_json:Error` implements `serde::de/ser::Error`.
Removed it in #15.

**Comment by jgraef** [comment]
Any last wishes before I release?

**Comment by martsokha** [comment]
There are a few things, but that's for another time, e.g. `reqwest`-like error type or `#[must_use]`.

**Comment by martsokha** [comment]
@jgraef Hey, are there any updates? I'm trying to publish https://github.com/EinStack/glide-rs, but it's not possible due to a missing version tag.

**Comment by jgraef** [comment]
@martsokha Version 0.4.0 is published
