### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by dev-ardi** [jgraef/reqwest-websocket#3]
```rs
 tracing::debug!("server responded with invalid Upgrade header");
 return Err(Error::HandshakeFailed);
```

## The problem

1. We can't match on the variants of the enum
2. The error message is a generic "websocket upgrade failed". 
3. If you're not using tracing you have no idea of what's going wrong.
4. You force a concrete tracing configuration. What if to me it's not `debug` but `error`?

## The solution

you should make the reason an enum variant, one per variant.

```rs
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("server responded with invalid Upgrade header")]
    InvalidUpgradeHeader,
```

**Comment by jgraef** [comment]
This is of course a good suggestion. We did already introduce a [`HandshakeError`](https://github.com/jgraef/reqwest-websocket/blob/22c4289b0c0b9411be383017e7b5a99b514aff57/src/native.rs#L83).

Does this resolve your issue?

**Comment by dev-ardi** [comment]
Is that for an unreleased version?

**Comment by jgraef** [comment]
Yes, it's on the current master branch, and it isn't released yet.
