### ISSUE TITLE
latest support for reqwest 0.12 is not working in WASM mode

### ISSUE THREAD

**Issue by radix** [jgraef/reqwest-websocket#7]
there seem to be two problems:

- `ClientBuilder` has no `http1_only` method in WASM mode
- `UpgradeResponse`'s `into_inner` is trying to access `response` on a `WebSysWebSocketStream`, which does not exist.

**Comment by jgraef** [comment]
This was fixed by your PR #8. The errors I got when building for WASM were because of missing feature flags for web_sys. This is fixed now.

**Comment by radix** [comment]
awesome, thank you very much @jgraef !
